# Generated by Django 3.2.10 on 2021-12-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffcatogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogoryname', models.CharField(max_length=30)),
            ],
        ),
    ]
