# Generated by Django 3.2.10 on 2021-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0004_doctoradd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoradd',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
