# Generated by Django 3.2.10 on 2021-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0005_alter_doctoradd_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoradd',
            name='quali',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
