# Generated by Django 3.2.10 on 2021-12-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0006_alter_doctoradd_quali'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoradd',
            name='status',
            field=models.IntegerField(default=None),
        ),
    ]
