# Generated by Django 3.2.10 on 2021-12-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0007_doctoradd_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('sunday', models.IntegerField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsadmin.doctoradd')),
            ],
        ),
    ]
