# Generated by Django 3.2.10 on 2021-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0008_doctorop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorop',
            name='friday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctorop',
            name='monday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctorop',
            name='saturday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctorop',
            name='sunday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctorop',
            name='thursday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctorop',
            name='tuesday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctorop',
            name='wednesday',
            field=models.IntegerField(blank=True),
        ),
    ]
