# Generated by Django 3.2.10 on 2022-01-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0010_doctortimings'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsadmin.doctoradd')),
            ],
        ),
    ]
