# Generated by Django 3.2.10 on 2022-01-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0011_dropschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctortimings',
        ),
    ]
