# Generated by Django 3.2.10 on 2022-01-01 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0012_delete_doctortimings'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctortimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(default=datetime.time(16, 0))),
                ('end', models.TimeField(default=datetime.time(16, 0))),
                ('pertime', models.IntegerField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsadmin.doctoradd')),
            ],
        ),
    ]
