# Generated by Django 3.2.10 on 2022-01-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0015_alter_dropschedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffadd',
            name='status',
            field=models.IntegerField(default=None),
        ),
    ]
