# Generated by Django 3.2.10 on 2022-01-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('dep', models.CharField(max_length=30)),
                ('doc', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
