# Generated by Django 3.2.10 on 2022-01-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsadmin', '0016_staffadd_status'),
        ('hmsreception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsadmin.dropschedule'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsadmin.departmentadd'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsadmin.doctoradd'),
        ),
    ]
